### ISSUE TITLE
Needs to specify Swift Language Version

### ISSUE THREAD

**Issue by imryan** [mukeshthawani/TriLabelView#11]
When building for Objective-C in Xcode 9, I receive an error due to an unspecified/unsupported Swift version. The fix is just to go into `Build Settings` > `Swift Compiler - Language` > `Swift Language Version` and then set it there.

**Comment by mukeshthawani** [comment]
Please try the latest version(1.0.0) it should work fine.

**Comment by imryan** [comment]
@mukeshthawani Still getting the same error.
```
Check dependencies:

The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
```

**Comment by mukeshthawani** [comment]
Ok I will check

**Comment by mukeshthawani** [comment]
@imryan if it's working in the latest version then we can close this issue.

**Comment by imryan** [comment]
@mukeshthawani Yeah I agree, let's just close this
