### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [mukeshthawani/TriLabelView#16]
Hi @mukeshthawani  I am a graphic designer and I would like to contribute to your good project by designing a logo for it as i have noticed it doesn't have one yet..I will be doing it as a gift for free, I just need your permission first before I begin..Hoping for your positive feedback. Thanks and best regards!

- Tobaloidee

**Comment by mukeshthawani** [comment]
Hi @Tobaloidee 
Thanks for the proposal. Sure go ahead 👍

**Comment by Tobaloidee** [comment]
Thank you for permitting me. Will start designing now and show you here when done Sir..

**Comment by Tobaloidee** [comment]
Hello @mukeshthawani  here's what i came up with...I hope you like it

![trilabelview-01](https://user-images.githubusercontent.com/36028424/42708319-89ea089e-870f-11e8-960a-471045585351.png)

**Comment by mukeshthawani** [comment]
All are good but we can go ahead with the third one. It's looking really good in the dark background. 👍

**Comment by Tobaloidee** [comment]
Thanks Sir..im glad you liked it..I will prepare the files and make a PR with it..

**Comment by Tobaloidee** [comment]
Sir before i finalize it i just want to show you this option for the third version that you have chosen..you might like this, if not then its the original third version. I made a custom "T" to be uniform with the typeface

![trilabelviewpres3-01](https://user-images.githubusercontent.com/36028424/42723703-ac9ad1c6-8795-11e8-821a-44552acc8fda.png)

**Comment by mukeshthawani** [comment]
Yeah, it looks good.

Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tobaloidee** [comment]
okay Sir..thanks for the quick response! will finalize it now and make a PR :+1:

**Comment by Tobaloidee** [comment]
I made a PR #17 already @mukeshthawani  Thanks so much and best regards to the project!

**Comment by mukeshthawani** [comment]
Merged
