### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by nsleche** [mukeshthawani/TriLabelView#5]
it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by mukeshthawani** [comment]
Hey, you can check swift-3 branch I have updated it.

**Comment by mukeshthawani** [comment]
Released [v0.3.3](https://github.com/mukeshthawani/TriLabelView/releases/tag/0.3.3) with swift-3 support.
