### ISSUE TITLE
it's not work with collectionView

### ISSUE THREAD

**Issue by abdulelah1** [mukeshthawani/TriLabelView#8]
![simulator screen shot dec 1 2016 10 07 32 pm](https://cloud.githubusercontent.com/assets/21056071/20808150/98f14f64-b812-11e6-83dc-2ef70263d7ba.png)

**Comment by abdulelah1** [comment]
xcode 8
iOS 10.1
swift 3

**Comment by mukeshthawani** [comment]
Hi,

What is the exact issue? It is not visible or it is out of bound? 
In one cell I can see it is not aligned properly and in another, it is not present. And if you can show me your code where you are using this, it would be helpful to know more.

Thanks

**Comment by abdulelah1** [comment]
The Label just appear in the last cell

**Comment by mukeshthawani** [comment]
Please check the demo app for examples.

**Comment by mukeshthawani** [comment]
Closing this for now.

**Comment by mukeshthawani** [comment]
Open this if you are still facing any issues.
